highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://rmanak.github.io/jekkly
author: Arman Akbarian

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /jekkly/
title: Arman Akbarian Resume
name: Arman Akbarian
email: arman2@gmail.com
email_full: mailto:arman2@gmail.com
avator: profile.jpg
website: rmanak.github.io
linkedin: armanakbarian
website_full: https://rmanak.github.io/
github: rmanak
#twitter: twitter
tel: +1 778 320 5515
tel_full: tel:+17783205515
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
#address: Vancouver
#postcode: V6T 1Z1
city: Vancouver
country: Canada
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
